### ISSUE TITLE
clash config template

### ISSUE THREAD

**Issue by zjy4fun** [zjy4fun/science#1]
```
# DNS 配置可自行修改
port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver: 
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

# 当前 13 个主流协议节点配置模版，按需求修改，如不需要使用某协议节点，则无需删除，确保代理分流中没有该节点即可
proxies:
- name: trojan-tcp-tls                            # 可以自定义节点名称
  type: trojan
  server: www.baidu.com                          # 解析的域名
  port: 443                                      # 自定义端口
  password: password                              # 自定义认证密码
  client-fingerprint: chrome
  udp: true
  sni: swww.baidu.com                              # SNI 域名，与上面 server 字段的地址一致
  alpn:
    - h2
    - http/1.1
  skip-cert-verify: false
# 分流组可自行创建或添加，proxies 参数下的节点名称，按需求自行增减，确保出现的节点名称在代理协议中可查找
proxy-groups:
- name: 负载均衡
  type: load-balance
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
    - trojan-tcp-tls

- name: 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
    - trojan-tcp-tls
    
- name: 🌍选择代理
  type: select
  proxies:
    - 负载均衡                                            # 自定义添加的节点名称
    - 自动选择
    - DIRECT
    - trojan-tcp-tls

# 代理规则可自行添加 
rules:
  - GEOIP,CN,DIRECT
  - MATCH,🌍选择代理

```
